services:
  alice-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alice_frontend
    ports:
      - "3000:80"
    networks:
      - alice_network
    restart: unless-stopped

networks:
  alice_network:
    external: true
    name: alice-backend_alice_network
